"""User-facing text constants for Lyume wizard — i18n support."""
import os

_LANG = os.environ.get("LYUME_LANG", "uk")

_STRINGS = {
    "uk": {
        "welcome_title": "Ласкаво просимо до Lyume Wizard",
        "welcome_body": "Цей майстер допоможе вам налаштувати вашу систему Lyume для роботи з великими мовними моделями.",
        "step_identity": "Особисті дані та назва проєкту",
        "step_backend": "Вибір бекенду (LLM)",
        "step_embedding": "Вибір моделі ембеддингів",
        "step_docker": "Перевірка Docker",
        "step_database": "Налаштування бази даних",
        "step_import": "Імпорт початкових даних (опціонально)",
        "step_summary": "Підсумок конфігурації",
        "back_hint": "(введіть 'b', щоб повернутися назад)",
        "checkpoint_found": "Знайдено попередню сесію налаштувань.",
        "checkpoint_continue": "Продовжити з місця, де ви зупинилися?",
        "step_progress": "Крок {current}/{total}: {title}",
        "agent_name": "Ім'я агента",
        "user_name": "Ім'я користувача",
        "scanning_backends": "Сканую локальні бекенди...",
        "found_backends": "Знайдені бекенди:",
        "no_backends_found": "Не знайдено жодного доступного локального бекенду LLM.",
        "pick_backend": "Виберіть (1-{n}) або 'm' для ручного вводу або 'b' назад",
        "manual_url": "Введіть URL бекенду",
        "llm_models": "LLM моделі:",
        "pick_model": "Виберіть модель або 'b' назад",
        "api_key": "API ключ (залиште порожнім якщо не потрібен)",
        "embed_models_available": "Доступні моделі ембеддингів:",
        "pick_embed_model": "Виберіть модель або 'b' назад",
        "no_embed_models": "Не знайдено моделей ембеддингів.",
        "embed_recommend": "Рекомендовано: nomic-embed-text-v1.5",
        "embed_download": "Завантажити (Ollama: ollama pull nomic-embed-text)",
        "embed_diff_url": "Використати інший URL",
        "embed_local_gguf": "Використати локальний GGUF файл",
        "embed_dims": "Розмірність ембеддингів: {dims}",
        "embed_test_fail": "Не вдалося протестувати ембеддинг: {err}",
        "embed_fetch_fail": "Не вдалося отримати моделі з {url}: {err}",
        "enter_gguf_path": "Введіть шлях до GGUF файлу",
        "embed_run_ollama": "Виконайте: ollama pull nomic-embed-text",
        "embed_then_restart": "Потім перезапустіть цей крок.",
        "embed_enter_url": "Введіть інший URL бекенду (або 'b' назад)",
        "embed_pick_option": "Виберіть опцію (1-3) або 'b' назад",
        "docker_ok": "Docker запущено",
        "docker_not_running": "Docker встановлено, але не запущено.",
        "docker_start_hint": "Запустіть: sudo systemctl start docker",
        "docker_retry": "[r] Повторити | [s] Пропустити",
        "docker_now_running": "Docker тепер запущено",
        "docker_not_installed": "Docker не встановлено.",
        "docker_purpose": "Docker запускає PostgreSQL для зберігання пам'яті.",
        "docker_install_time": "Встановлення займає ~2 хвилини.",
        "docker_restart": "[r] Перезапустити wizard | [s] Пропустити",
        "docker_compose_missing": "Docker Compose не встановлено.",
        "docker_compose_hint": "Docker Compose потрібен для запуску PostgreSQL.",
        "db_docker_option": "[1] Docker PostgreSQL (рекомендовано — нульова конфігурація)",
        "db_external_option": "[2] Зовнішній PostgreSQL",
        "db_choose": "Виберіть",
        "db_no_docker": "Docker не доступний. Використовуємо зовнішній PostgreSQL.",
        "db_waiting": "Очікую готовності PostgreSQL...",
        "db_not_ready": "Попередження: база даних може бути ще не готова",
        "db_start_fail": "Не вдалося запустити Docker PostgreSQL: {err}",
        "db_compose_not_found": "Docker Compose не знайдено.",
        "db_host": "PostgreSQL хост",
        "db_port": "PostgreSQL порт",
        "db_user": "PostgreSQL користувач",
        "db_password": "PostgreSQL пароль",
        "port_in_use": "Порт {port} зайнятий.",
        "port_suggest": "Використати {port} замість цього? [Y/n]",
        "port_custom": "Введіть порт вручну",
        "port_all_busy": "Не вдалося знайти вільний порт в діапазоні {start}-{end}.",
        "import_auto_scan": "[1] Авто-сканування",
        "import_enter_path": "[2] Ввести шлях",
        "import_skip": "[3] Пропустити",
        "import_choose": "Виберіть",
        "import_found": "Знайдено:",
        "import_not_found": "Не знайдено відомих шляхів пам'яті.",
        "import_enter": "Введіть шлях для імпорту",
        "import_path_missing": "Шлях не існує",
        "summary_title": "Підсумок конфігурації",
        "summary_redo_hint": "Хочете щось змінити? Введіть номер [bold](1-6)[/bold] щоб переробити крок.",
        "summary_confirm_hint": "Або натисніть [bold][c][/bold] щоб підтвердити  |  [bold][b][/bold] назад",
        "summary_choice": "Ваш вибір",
        "deps_installing": "Встановлюю залежності...",
        "deps_uv_found": "Знайдено uv — використовую uv sync",
        "deps_pip_fallback": "uv не знайдено — використовую pip",
        "deps_success": "Залежності встановлені",
        "deps_fail": "Не вдалося встановити залежності: {err}",
        "deps_retry": "Спробувати ще раз? [Y/n]",
        "deps_manual_hint": "Встановіть вручну:\n  cd {dir}\n  {cmd}",
        "service_ok": "Сервіс налаштовано успішно!",
        "service_fail": "Не вдалося налаштувати сервіс: {err}",
        "service_status": "Перевірити статус:",
        "service_logs": "Переглянути логи:",
        "proxy_port_check": "Перевіряю порт проксі ({port})...",
        "proxy_port_ok": "Порт {port} вільний",
        "openclaw_registering": "Реєструю агента в OpenClaw...",
        "openclaw_ok": "Агент зареєстрований в OpenClaw",
        "openclaw_not_found": "openclaw CLI не знайдено — пропускаю реєстрацію",
        "openclaw_fail": "Не вдалося зареєструвати агента: {err}",
        "restart_saved": "Прогрес збережено. Перезапустіть wizard після налаштування.",
        "summary_agent": "Агент",
        "summary_user": "Користувач",
        "summary_backend": "Бекенд",
        "summary_embedding": "Ембеддинг",
        "summary_database": "База даних",
        "summary_import": "Імпорт",
        "summary_sources": "{n} джерел(о) знайдено",
    },
    "en": {
        "welcome_title": "Welcome to Lyume Wizard",
        "welcome_body": "This wizard will help you set up your Lyume system for working with large language models.",
        "step_identity": "Identity & Project Name",
        "step_backend": "LLM Backend Selection",
        "step_embedding": "Embedding Model Selection",
        "step_docker": "Docker Check",
        "step_database": "Database Setup",
        "step_import": "Import Initial Data (optional)",
        "step_summary": "Configuration Summary",
        "back_hint": "(type 'b' to go back)",
        "checkpoint_found": "Previous setup session found.",
        "checkpoint_continue": "Continue from where you left off?",
        "step_progress": "Step {current}/{total}: {title}",
        "agent_name": "Agent name",
        "user_name": "User name",
        "scanning_backends": "Scanning local backends...",
        "found_backends": "Found backends:",
        "no_backends_found": "No available local LLM backends found.",
        "pick_backend": "Pick (1-{n}) or 'm' for manual or 'b' back",
        "manual_url": "Enter backend URL",
        "llm_models": "LLM models:",
        "pick_model": "Pick model or 'b' back",
        "api_key": "API key (leave empty if not needed)",
        "embed_models_available": "Embedding models available:",
        "pick_embed_model": "Pick model or 'b' back",
        "no_embed_models": "No embedding models found.",
        "embed_recommend": "Recommended: nomic-embed-text-v1.5",
        "embed_download": "Download (Ollama: ollama pull nomic-embed-text)",
        "embed_diff_url": "Use different URL",
        "embed_local_gguf": "Use local GGUF file",
        "embed_dims": "Embedding dimensions: {dims}",
        "embed_test_fail": "Could not test embedding: {err}",
        "embed_fetch_fail": "Could not fetch models from {url}: {err}",
        "enter_gguf_path": "Enter path to GGUF file",
        "embed_run_ollama": "Run: ollama pull nomic-embed-text",
        "embed_then_restart": "Then restart this step.",
        "embed_enter_url": "Enter different backend URL (or 'b' back)",
        "embed_pick_option": "Pick option (1-3) or 'b' back",
        "docker_ok": "Docker is running",
        "docker_not_running": "Docker installed but not running.",
        "docker_start_hint": "Start with: sudo systemctl start docker",
        "docker_retry": "[r] Retry | [s] Skip",
        "docker_now_running": "Docker is now running",
        "docker_not_installed": "Docker is not installed.",
        "docker_purpose": "Docker runs PostgreSQL for memory storage.",
        "docker_install_time": "Installation takes ~2 minutes.",
        "docker_restart": "[r] Restart wizard | [s] Skip",
        "docker_compose_missing": "Docker Compose is not installed.",
        "docker_compose_hint": "Docker Compose is needed to run PostgreSQL.",
        "db_docker_option": "[1] Docker PostgreSQL (recommended — zero config)",
        "db_external_option": "[2] External PostgreSQL",
        "db_choose": "Choose",
        "db_no_docker": "Docker not available. Using external PostgreSQL.",
        "db_waiting": "Waiting for PostgreSQL to be ready...",
        "db_not_ready": "Warning: database may not be ready yet",
        "db_start_fail": "Failed to start Docker PostgreSQL: {err}",
        "db_compose_not_found": "Docker Compose not found.",
        "db_host": "PostgreSQL host",
        "db_port": "PostgreSQL port",
        "db_user": "PostgreSQL user",
        "db_password": "PostgreSQL password",
        "port_in_use": "Port {port} is in use.",
        "port_suggest": "Use {port} instead? [Y/n]",
        "port_custom": "Enter port manually",
        "port_all_busy": "Could not find a free port in range {start}-{end}.",
        "import_auto_scan": "[1] Auto-scan",
        "import_enter_path": "[2] Enter path",
        "import_skip": "[3] Skip",
        "import_choose": "Choose",
        "import_found": "Found:",
        "import_not_found": "No known memory paths found.",
        "import_enter": "Enter path to import",
        "import_path_missing": "Path does not exist",
        "summary_title": "Configuration Summary",
        "summary_redo_hint": "Want to change something? Enter a number [bold](1-6)[/bold] to redo that step.",
        "summary_confirm_hint": "Or press [bold][c][/bold] to confirm  |  [bold][b][/bold] to go back",
        "summary_choice": "Your choice",
        "deps_installing": "Installing dependencies...",
        "deps_uv_found": "Found uv — using uv sync",
        "deps_pip_fallback": "uv not found — using pip",
        "deps_success": "Dependencies installed",
        "deps_fail": "Failed to install dependencies: {err}",
        "deps_retry": "Retry? [Y/n]",
        "deps_manual_hint": "Install manually:\n  cd {dir}\n  {cmd}",
        "service_ok": "Service configured successfully!",
        "service_fail": "Failed to configure service: {err}",
        "service_status": "Check status:",
        "service_logs": "View logs:",
        "proxy_port_check": "Checking proxy port ({port})...",
        "proxy_port_ok": "Port {port} is free",
        "openclaw_registering": "Registering agent in OpenClaw...",
        "openclaw_ok": "Agent registered in OpenClaw",
        "openclaw_not_found": "openclaw CLI not found — skipping registration",
        "openclaw_fail": "Failed to register agent: {err}",
        "restart_saved": "Progress saved. Restart wizard after setup.",
        "summary_agent": "Agent",
        "summary_user": "User",
        "summary_backend": "Backend",
        "summary_embedding": "Embedding",
        "summary_database": "Database",
        "summary_import": "Import",
        "summary_sources": "{n} source(s) found",
    },
}


def t(key: str, **kwargs) -> str:
    """Get translated string for current LYUME_LANG."""
    lang = _LANG if _LANG in _STRINGS else "uk"
    text = _STRINGS[lang].get(key, _STRINGS["uk"].get(key, key))
    if kwargs:
        return text.format(**kwargs)
    return text


# Backward-compatible constants (used in step title attributes)
STEP_IDENTITY = t("step_identity")
STEP_BACKEND = t("step_backend")
STEP_EMBEDDING = t("step_embedding")
STEP_DOCKER = t("step_docker")
STEP_DATABASE = t("step_database")
STEP_IMPORT = t("step_import")
STEP_SUMMARY = t("step_summary")
